# #FILENAME:.air.toml:merge
root = "."
tmp_dir = "tmp"

[build]
  bin = "tmp/main"
  cmd = "go build -o tmp/main ."
  delay = 1000
  exclude_dir = ["tmp", "vendor", "node_modules", "generated"]
  exclude_file = []
  exclude_regex = []
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html", "json", "yaml", "yml"]
  kill_delay = "0s"
  log = "build-errors.log"
  send_interrupt = false
  stop_on_error = false

[dev]
  after = ["go mod tidy"]
  before = []
  cmd = ["tmp/main"]
  delay = 0
  kill_delay = "500ms"
  restart_on_change = true